import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.7.1'
import { corsHeaders, handleCors, jsonResponse, errorResponse } from '../_shared/cors.ts'
import { createLogger } from '../_shared/logger.ts'
import { authenticateRequest, AuthError } from '../_shared/authMiddleware.ts'
import { checkRateLimit, extractIdentifier, rateLimitHeaders } from '../_shared/rateLimit.ts'
import { handleHealthCheck } from '../_shared/health.ts'

const log = createLogger('generate-media')

const GEMINI_API_KEY = Deno.env.get('GEMINI_API_KEY') || ''
const ELEVENLABS_API_KEY = Deno.env.get('ELEVENLABS_API_KEY') || ''
const SUPABASE_URL = Deno.env.get('SUPABASE_URL') || ''
const SUPABASE_SERVICE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') || ''

const ELEVENLABS_VOICE_ID = '21m00Tcm4TlvDq8ikWAM'
const ELEVENLABS_MODEL_ID = 'eleven_multilingual_v2'

async function generateImageGemini(prompt: string): Promise<{ base64: string; mimeType: string }> {
  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?key=${GEMINI_API_KEY}`

  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      contents: [{
        parts: [{ text: prompt }]
      }],
      generationConfig: {
        responseModalities: ['TEXT', 'IMAGE'],
        temperature: 0.4,
      }
    })
  })

  if (!response.ok) {
    const errText = await response.text()
    throw new Error(`Gemini API error ${response.status}: ${errText.substring(0, 300)}`)
  }

  const data = await response.json()
  const parts = data?.candidates?.[0]?.content?.parts || []

  const imagePart = parts.find((p: any) => p.inlineData)
  if (!imagePart) {
    throw new Error('No image generated by Gemini')
  }

  return {
    base64: imagePart.inlineData.data,
    mimeType: imagePart.inlineData.mimeType || 'image/png'
  }
}

async function generateAudioElevenLabs(text: string, voiceId?: string): Promise<Uint8Array> {
  const vId = voiceId || ELEVENLABS_VOICE_ID
  const url = `https://api.elevenlabs.io/v1/text-to-speech/${vId}`

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'xi-api-key': ELEVENLABS_API_KEY,
      'Content-Type': 'application/json',
      'Accept': 'audio/mpeg'
    },
    body: JSON.stringify({
      text,
      model_id: ELEVENLABS_MODEL_ID,
      voice_settings: {
        stability: 0.5,
        similarity_boost: 0.75
      }
    })
  })

  if (!response.ok) {
    const errText = await response.text()
    throw new Error(`ElevenLabs API error ${response.status}: ${errText.substring(0, 300)}`)
  }

  const arrayBuffer = await response.arrayBuffer()
  return new Uint8Array(arrayBuffer)
}

async function uploadToStorage(
  supabase: any,
  bucketId: string,
  path: string,
  data: Uint8Array | string,
  contentType: string
): Promise<string> {
  const isBase64 = typeof data === 'string'

  const { error: uploadError } = await supabase.storage
    .from(bucketId)
    .upload(path, isBase64 ? Uint8Array.from(atob(data as string), c => c.charCodeAt(0)) : data as Uint8Array, {
      contentType,
      upsert: true
    })

  if (uploadError) {
    throw new Error(`Storage upload failed: ${uploadError.message}`)
  }

  const { data: urlData } = supabase.storage.from(bucketId).getPublicUrl(path)
  return urlData?.publicUrl || ''
}

async function findExistingAsset(supabase: any, unitId: string, type: string, promptHash: string): Promise<string | null> {
  const { data } = await supabase
    .from('assets')
    .select('public_url')
    .eq('unit_id', unitId)
    .eq('type', type)
    .eq('metadata->>promptHash', promptHash)
    .limit(1)

  if (data && data.length > 0 && data[0].public_url) {
    return data[0].public_url
  }
  return null
}

async function saveAssetRecord(supabase: any, unitId: string, type: string, prompt: string, storagePath: string, publicUrl: string, promptHash: string): Promise<void> {
  const { error } = await supabase.from('assets').insert({
    unit_id: unitId,
    type,
    prompt,
    storage_path: storagePath,
    public_url: publicUrl,
    metadata: { promptHash }
  })

  if (error) {
    log.warn('asset_record_save_failed', { error: error.message })
  }
}

function simpleHash(str: string): string {
  let hash = 0
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i)
    hash = ((hash << 5) - hash) + char
    hash = hash & hash
  }
  return Math.abs(hash).toString(36)
}

serve(async (req) => {
  const startTime = Date.now()

  try {
    const healthResponse = handleHealthCheck(req)
    if (healthResponse) return healthResponse

    const corsResponse = handleCors(req)
    if (corsResponse) return corsResponse

    const identifier = extractIdentifier(req)
    const rateLimit = checkRateLimit(identifier, { maxRequests: 15, windowMs: 60 * 1000 })
    if (!rateLimit.allowed) {
      log.warn('rate_limited', { metadata: { identifier } })
      return errorResponse('Rate limit exceeded.', 429, rateLimitHeaders(rateLimit.remaining, rateLimit.retryAfterMs))
    }

    let userId: string | undefined
    try {
      const auth = await authenticateRequest(req)
      userId = auth.userId
    } catch (authErr) {
      if (authErr instanceof AuthError) {
        log.warn('auth_failed', { error: authErr.message })
        return errorResponse(authErr.message, authErr.status)
      }
    }

    const body = await req.json()
    const { action, unitId, prompt, text, voiceId, force } = body

    if (!unitId) {
      return errorResponse('Missing unitId', 400)
    }

    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY)

    if (action === 'generate-image' || (!action && prompt)) {
      if (!prompt) {
        return errorResponse('Missing prompt for image generation', 400)
      }

      if (!GEMINI_API_KEY) {
        return errorResponse('GEMINI_API_KEY not configured', 503)
      }

      const promptHash = simpleHash(prompt)

      if (!force) {
        const existingUrl = await findExistingAsset(supabase, unitId, 'image', promptHash)
        if (existingUrl) {
          log.info('image_cache_hit', { userId, metadata: { unitId, promptHash } })
          return jsonResponse({ success: true, url: existingUrl, cached: true }, 200, rateLimitHeaders(rateLimit.remaining, 0))
        }
      }

      log.info('image_gen_start', { userId, metadata: { unitId, promptLength: prompt.length } })

      const imagePrompt = `Educational illustration for children's English lesson: ${prompt}. Style: colorful, cartoon, child-friendly, clean background, no text.`
      const result = await generateImageGemini(imagePrompt)

      const ext = result.mimeType.includes('png') ? 'png' : result.mimeType.includes('webp') ? 'webp' : 'jpg'
      const storagePath = `${unitId}/images/${promptHash}.${ext}`
      const publicUrl = await uploadToStorage(supabase, 'generated-media', storagePath, result.base64, result.mimeType)

      await saveAssetRecord(supabase, unitId, 'image', prompt, storagePath, publicUrl, promptHash)

      log.info('image_gen_complete', { userId, durationMs: Date.now() - startTime, metadata: { unitId } })
      return jsonResponse({ success: true, url: publicUrl, cached: false }, 200, rateLimitHeaders(rateLimit.remaining, 0))
    }

    if (action === 'generate-audio' || (!action && text)) {
      if (!text) {
        return errorResponse('Missing text for audio generation', 400)
      }

      if (!ELEVENLABS_API_KEY) {
        return errorResponse('ELEVENLABS_API_KEY not configured', 503)
      }

      const promptHash = simpleHash(`audio:${text}:${voiceId || ELEVENLABS_VOICE_ID}`)

      if (!force) {
        const existingUrl = await findExistingAsset(supabase, unitId, 'audio', promptHash)
        if (existingUrl) {
          log.info('audio_cache_hit', { userId, metadata: { unitId, promptHash } })
          return jsonResponse({ success: true, url: existingUrl, cached: true }, 200, rateLimitHeaders(rateLimit.remaining, 0))
        }
      }

      log.info('audio_gen_start', { userId, metadata: { unitId, textLength: text.length } })

      const audioData = await generateAudioElevenLabs(text, voiceId)
      const storagePath = `${unitId}/audio/${promptHash}.mp3`
      const publicUrl = await uploadToStorage(supabase, 'generated-media', storagePath, audioData, 'audio/mpeg')

      await saveAssetRecord(supabase, unitId, 'audio', text, storagePath, publicUrl, promptHash)

      log.info('audio_gen_complete', { userId, durationMs: Date.now() - startTime, metadata: { unitId } })
      return jsonResponse({ success: true, url: publicUrl, cached: false }, 200, rateLimitHeaders(rateLimit.remaining, 0))
    }

    if (action === 'batch') {
      const { images, audios } = body

      if (!images && !audios) {
        return errorResponse('Missing images or audios array for batch generation', 400)
      }

      const results: { images: Record<string, string>; audios: Record<string, string> } = {
        images: {},
        audios: {}
      }

      if (images && Array.isArray(images)) {
        if (!GEMINI_API_KEY) {
          return errorResponse('GEMINI_API_KEY not configured', 503)
        }

        for (const item of images) {
          try {
            const promptHash = simpleHash(item.prompt)

            if (!force) {
              const existingUrl = await findExistingAsset(supabase, unitId, 'image', promptHash)
              if (existingUrl) {
                results.images[item.key || item.prompt] = existingUrl
                continue
              }
            }

            const imagePrompt = `Educational illustration for children's English lesson: ${item.prompt}. Style: colorful, cartoon, child-friendly, clean background, no text.`
            const result = await generateImageGemini(imagePrompt)

            const ext = result.mimeType.includes('png') ? 'png' : result.mimeType.includes('webp') ? 'webp' : 'jpg'
            const storagePath = `${unitId}/images/${promptHash}.${ext}`
            const publicUrl = await uploadToStorage(supabase, 'generated-media', storagePath, result.base64, result.mimeType)

            await saveAssetRecord(supabase, unitId, 'image', item.prompt, storagePath, publicUrl, promptHash)
            results.images[item.key || item.prompt] = publicUrl
          } catch (err: any) {
            log.warn('batch_image_failed', { error: err.message, metadata: { prompt: (item.prompt || '').substring(0, 50) } })
            results.images[item.key || item.prompt] = ''
          }
        }
      }

      if (audios && Array.isArray(audios)) {
        if (!ELEVENLABS_API_KEY) {
          log.warn('elevenlabs_not_configured_batch')
        } else {
          for (const item of audios) {
            try {
              const promptHash = simpleHash(`audio:${item.text}:${item.voiceId || ELEVENLABS_VOICE_ID}`)

              if (!force) {
                const existingUrl = await findExistingAsset(supabase, unitId, 'audio', promptHash)
                if (existingUrl) {
                  results.audios[item.key || item.text] = existingUrl
                  continue
                }
              }

              const audioData = await generateAudioElevenLabs(item.text, item.voiceId)
              const storagePath = `${unitId}/audio/${promptHash}.mp3`
              const publicUrl = await uploadToStorage(supabase, 'generated-media', storagePath, audioData, 'audio/mpeg')

              await saveAssetRecord(supabase, unitId, 'audio', item.text, storagePath, publicUrl, promptHash)
              results.audios[item.key || item.text] = publicUrl
            } catch (err: any) {
              log.warn('batch_audio_failed', { error: err.message, metadata: { text: (item.text || '').substring(0, 50) } })
              results.audios[item.key || item.text] = ''
            }
          }
        }
      }

      const imageCount = Object.keys(results.images).length
      const audioCount = Object.keys(results.audios).length
      log.info('batch_complete', { userId, durationMs: Date.now() - startTime, metadata: { unitId, imageCount, audioCount } })

      return jsonResponse({ success: true, results }, 200, rateLimitHeaders(rateLimit.remaining, 0))
    }

    return errorResponse('Unknown action. Use generate-image, generate-audio, or batch.', 400)

  } catch (error: any) {
    log.error('generate_media_failed', { error: error.message, durationMs: Date.now() - startTime })
    return errorResponse(error.message)
  }
})
