-- =====================================================================
-- 20260818214857 — reconciliation marker (no-op)
--
-- This version was applied directly on the CLOUD database via the
-- dashboard / Management API on 2026-08-18, before being codified on
-- disk. Its content is the student-passports schema, codified in
-- 20260819000001_student_passports.sql (student_passports,
-- passport_secrets, profiles.username, column-level grants, two-arg
-- can_manage_class).
--
-- Verified 2026-08-26 (FIXPLAN_F P0.1): cloud objects match the disk
-- file (student_passports 15 cols, passport_secrets 3 cols, indexes
-- idx_student_passports_* all present); no disk-only versions exist.
-- This file exists only so that `supabase migration list` / `db push`
-- version sets match exactly between disk and cloud. It deliberately
-- contains no SQL.
-- =====================================================================
