// games-v3 BATCH fixtures — one throwaway teacher/class/unit whose flow contains
// ALL 18 remaining audited game types, with a real exercise pool generated by
// the deployed generate-exercises function (so pool-driven games render real
// content on the board). Pairs with games-v3-batch-shots.ts.
//
//   tsx scripts/testing/games-v3-batch-fixtures.ts --setup
//   tsx scripts/testing/games-v3-batch-fixtures.ts --teardown
//
// State: /tmp/games-v3-batch.json

import fs from 'node:fs';
import crypto from 'node:crypto';

try { process.loadEnvFile('.env'); } catch { /* already set */ }

const SUPABASE_URL = process.env.VITE_SUPABASE_URL || '';
const ANON_KEY = process.env.VITE_SUPABASE_ANON_KEY || '';
const PAT = process.env.SUPABASE_ACCESS_TOKEN || '';
const PROJECT_REF = 'xsdnzijketjnzhakqtit';
const STATE = '/tmp/games-v3-batch.json';

if (!SUPABASE_URL || !ANON_KEY || !PAT) {
  console.error('Missing env: VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY / SUPABASE_ACCESS_TOKEN');
  process.exit(2);
}

async function sql(query: string, attempt = 0): Promise<any[]> {
  const res = await fetch(`https://api.supabase.com/v1/projects/${PROJECT_REF}/database/query`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${PAT}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ query }),
  });
  if (!res.ok) {
    const text = await res.text();
    // Transient Management-API hiccups (HTML error pages / 5xx / 429) — back off and retry.
    if (attempt < 4 && (res.status >= 500 || res.status === 429 || text.trimStart().startsWith('<'))) {
      await new Promise((r) => setTimeout(r, 5000 * (attempt + 1)));
      return sql(query, attempt + 1);
    }
    throw new Error(`SQL failed (${res.status}): ${text.slice(0, 200)}`);
  }
  const body = await res.json();
  return Array.isArray(body) ? body : [];
}

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const j = (o: unknown) => q(JSON.stringify(o));

const KIDS = ['Alice', 'Ben', 'Coco', 'Dudu', 'Emma', 'Fang', 'Gigi', 'Hugo'];
const WORDS: Array<{ word: string; zh: string; def: string; ex: string }> = [
  { word: 'tractor', zh: '拖拉机', def: 'a farm vehicle', ex: 'The tractor is big.' },
  { word: 'leaf', zh: '叶子', def: 'part of a plant', ex: 'A green leaf falls.' },
  { word: 'rock', zh: '岩石', def: 'a big stone', ex: 'I sit on the rock.' },
  { word: 'river', zh: '河', def: 'flowing water', ex: 'The river is long.' },
  { word: 'apple', zh: '苹果', def: 'a red fruit', ex: 'I eat an apple.' },
  { word: 'garden', zh: '花园', def: 'a place with flowers', ex: 'My garden is small.' },
];

const img = (w: string) => `https://picsum.photos/seed/${w}/400/300`;

/** The 18 audited game types in numeric order (index 0 = slide 1; INTRO first). */
const GAME_BLOCKS: Array<[string, Record<string, unknown>]> = [
  ['MEDIA_PLAYER', { title: 'Working in the Jungle' }],
  ['STORY_STAGE', {}],
  ['LISTEN_TAP', {}],
  ['FLASH_MATCH', {}],
  ['UNSCRAMBLE', {}],
  ['I_SAY_YOU_SAY', {}],
  ['GRAMMAR_LAB', {}],
  ['WORD_DETECTIVE', {}],
  ['SOUND_LAB', {}],
  ['STORY_QUEST', {}],
  ['SENTENCE_LAB', {}],
  ['PHONICS_ARENA', {}],
  ['MEMORY_LAB', {}],
  ['CLASS_RALLY', {}],
  ['FAST_VOCAB', {}],
  ['WORD_SEARCH', { rounds: 3, wordsPerRound: 5, seconds: 120, mode: 'open', preset: 'explorer' }],
  ['SPELLING_BEE', { wordsPerTurn: 3, timerSeconds: 15 }],
  ['COMIC_PANELS', {}],
  ['VOCAB_BLITZ', {}],
];

async function setup() {
  const stamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const password = crypto.randomBytes(12).toString('hex');
  const prefix = `gamesv3b-${stamp}`;
  const email = `${prefix}.teacher@passport.local`;

  let body: any = null;
  for (let attempt = 0; attempt < 4; attempt++) {
    const res = await fetch(`${SUPABASE_URL}/auth/v1/signup`, {
      method: 'POST',
      headers: { apikey: ANON_KEY, 'Content-Type': 'application/json' },
      body: JSON.stringify({ email, password }),
    });
    const text = await res.text();
    try { body = JSON.parse(text); } catch { body = null; }
    if (res.ok && body?.user?.id) break;
    if (attempt === 3) throw new Error(`signup (${res.status}): ${text.slice(0, 200)}`);
    await new Promise((r) => setTimeout(r, 5000 * (attempt + 1)));
  }
  if (!body?.user?.id) throw new Error('signup: no user id');
  const teacherId: string = body.user.id;
  await sql(`UPDATE public.profiles SET full_name = 'Games V3 Batch Camera', role = 'teacher'::public.user_role WHERE id = ${q(teacherId)}`);

  const classId = crypto.randomUUID();
  await sql(`INSERT INTO public.classes (id, name, teacher_id, code, is_active)
             VALUES (${q(classId)}, ${q(`${prefix} class`)}, ${q(teacherId)}, ${q(stamp.slice(-6))}, true)`);
  for (const kid of KIDS) {
    await sql(`INSERT INTO public.roster_students (class_id, teacher_id, display_name)
               VALUES (${q(classId)}, ${q(teacherId)}, ${q(kid)})`);
  }

  const unitId = crypto.randomUUID();
  const vocabRows = WORDS.map((w, i) => `(${q(unitId)}, ${i}, ${q(w.word)}, ${q(w.def)}, ${q(w.ex)}, ${q(w.zh)}, ${q(img(w.word))})`).join(', ');
  const grammarRows = [
    // two simple rules so GRAMMAR_LAB / grammar shells have real content
    `(${q(unitId)}, 0, 'Present Simple', 'We use it for things we do every day.', ${j(['She walks to school.', 'They play football.'])}, 'Subject + verb(s)', ${j([{ original: 'She walk to school', transformed: 'She walks to school' }, { original: 'They plays football', transformed: 'They play football' }])}, ${j([{ wrong: 'She walk to school', correct: 'She walks to school' }])})`,
    `(${q(unitId)}, 1, 'Can / Cannot', 'Use can to say what is possible.', ${j(['Lions can run fast.', 'Fish cannot fly.'])}, 'Subject + can + verb', ${j([{ original: 'Lions can swims', transformed: 'Lions can swim' }])}, ${j([{ wrong: 'Fish can fly', correct: 'Fish cannot fly' }])})`,
  ].join(', ');

  const manifest = {
    title: 'Games V3 Batch Unit',
    vocabulary: WORDS.map((w) => ({
      word: w.word, definition: w.def, example_sentence: w.ex,
      translation: w.zh, l1_translation: w.zh, image_url: img(w.word),
    })),
  };
  const flow = [
    { id: crypto.randomUUID(), type: 'INTRO_SPLASH', title: 'Unit Intro', data: {} },
    ...GAME_BLOCKS.map(([type, data]) => ({ id: crypto.randomUUID(), type, title: type, data })),
  ];
  await sql(`INSERT INTO public.units (id, teacher_id, title, level, status, topic, manifest, flow)
             VALUES (${q(unitId)}, ${q(teacherId)}, ${q(`GAMES-V3 BATCH ${stamp}`)}, 'A1', 'Active', 'camera', ${j(manifest)}, ${j(flow)})`);
  await sql(`INSERT INTO public.vocabulary_items (unit_id, order_index, word, definition, example_sentence, l1_translation, image_url)
             VALUES ${vocabRows}`);
  await sql(`INSERT INTO public.grammar_rules (unit_id, order_index, rule, explanation, examples, pattern_template, transformation_pairs, error_examples)
             VALUES ${grammarRows}`);
  await sql(`INSERT INTO public.classroom_sessions (teacher_id, class_id, unit_id, current_index, status)
             VALUES (${q(teacherId)}, ${q(classId)}, ${q(unitId)}, 1, 'LIVE')`);

  const state = { email, password, teacherId, classId, unitId, prefix };
  fs.writeFileSync(STATE, JSON.stringify(state, null, 2));
  console.log('BATCH SETUP OK');
  console.log(JSON.stringify(state, null, 2));
}

async function teardown() {
  const s = JSON.parse(fs.readFileSync(STATE, 'utf-8'));
  try {
    await sql(`DELETE FROM public.classroom_sessions WHERE teacher_id = ${q(s.teacherId)}`);
    await sql(`DELETE FROM public.roster_students WHERE teacher_id = ${q(s.teacherId)}`);
    await sql(`DELETE FROM public.classes WHERE id = ${q(s.classId)}`);
    await sql(`DELETE FROM public.units WHERE id = ${q(s.unitId)}`);
    await sql(`DELETE FROM auth.users WHERE id = ${q(s.teacherId)}`); // cascades profiles
    fs.unlinkSync(STATE);
    console.log('BATCH TEARDOWN OK');
  } catch (e: any) {
    console.error(`teardown warning: ${e.message}`);
    process.exit(1);
  }
}

const mode = process.argv[2];
if (mode === '--setup') setup().catch((e) => { console.error(e.message); process.exit(1); });
else if (mode === '--teardown') teardown();
else if (mode === '--pool') { // separate step: generate the exercise pool as the fixture teacher
  import('./games-v3-batch-pool.mjs');
} else { console.error('usage: --setup | --teardown'); process.exit(2); }
